apiVersion: v1
entries:
  pmm:
  - apiVersion: v2
    appVersion: 2.41.2
    created: "2024-04-24T13:21:09.11444772Z"
    description: A Helm chart for Percona Monitoring and Management (PMM)
    digest: 27157d098350b25be30818c1bac282470e9003221f2244240c65173a569f0611
    home: https://github.com/percona/pmm
    icon: https://www.percona.com/sites/default/files/pmm-logo.png
    keywords:
    - PMM
    - Monitoring
    maintainers:
    - email: tomislav.plavcic@percona.com
      name: tplavcic
    - email: nurlan.moldomurov@percona.com
      name: bupychuk
    - email: sergey.pronin@percona.com
      name: spron-in
    name: pmm
    type: application
    urls:
    - https://pmiriyev.github.io/percona-helm-charts/pmm-1.3.13.tgz
    version: 1.3.13
generated: "2024-04-24T13:21:09.113626954Z"
