name: Publish Helm Charts

on:
  push:
    branches:
      - publish
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Package Helm Charts
      run: |
        mkdir ./chart-packages
        for dir in charts/*; do
          if [ -d "$dir" ]; then
            helm package "$dir" --destination ./chart-packages
          fi
        done

    - name: Publish Helm Charts
      run: |
        git fetch origin gh-pages
        git checkout gh-pages
        mkdir -p charts
        mv ./chart-packages/* charts/
        helm repo index charts/ --url https://pmiriyev.github.io/percona-helm-charts/
        git add charts/
        git commit -m "Publish Helm charts"
        git push origin gh-pages