name: Publish Helm Charts

on:
  push:
    branches:
      - publish

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
      # Package Helm charts
      - name: Package Helm charts
        run: |
          helm package charts/pmm --destination public/
      
      # Generate Helm repo index
      - name: Generate Helm repo index
        run: |
          helm repo index public --url https://pmiriyev.github.io/percona-helm-charts/

      # Release Helm charts using chart-releaser-action
      - name: Release Helm charts
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: public/
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}