name: Publish Helm Charts

on:
  push:
    branches:
      - publish

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
      # Package Helm charts
      - name: Package Helm charts
        run: |
          helm package charts/pmm --destination .

      # Move packaged charts to docs directory
      - name: Move charts to docs directory
        run: |
          mkdir -p .charts
          mv *.tgz .charts/
      
      # Generate Helm repo index
      - name: Generate Helm repo index
        run: |
          helm repo index .charts --url https://pmiriyev.github.io/percona-helm-charts/

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Commit and push changes
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Helm charts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Configure git
      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Parviz"
      
      # Push changes to GitHub Pages branch
      - name: Push changes to GitHub Pages
        run: |
          git checkout publish
          git add .
          git commit -m "Publish Helm charts"
          git push origin publish:gh-pages
