name: Publish Helm Charts

on:
  push:
    branches:
      - publish

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
      # Package Helm charts
      - name: Package Helm charts
        run: |
          helm package charts/pmm --destination public/

      - name: Publish Helm Chart to gh-pages
        run: |
          git fetch --all
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
          helm repo index charts --url https://pmiriyev.github.io/percona-helm-charts/
          git add public
          git commit -m "Publish Helm charts"
          git push origin gh-pages